// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTX.Data.ServerData;

#nullable disable

namespace TTX.Data.ServerData.Migrations
{
    [DbContext(typeof(AssetsContext))]
    partial class AssetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("TTX.Data.ServerData.Entities.AssetRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Crumbs")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ItemId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MediaDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrimaryAudioBitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryAudioCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimarySubtitleCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PrimaryVideoBitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryVideoCodec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryVideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryVideoWidth")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SHA256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SimilarIgnore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TTX.Data.ServerData.Entities.TagRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
